<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CarMoneyLab.Application\CarMoneyLab.Application.csproj" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
  </ItemGroup>
</Project>
